CREATE TABLE PETINF (
 PETID                 int ,
 CONSTRAINT PETINF_PRIMARY_KEY PRIMARY KEY (PETID),
 PETNAME               VARCHAR(14),
  
 PETTYPE               VARCHAR(13),
 PETAGE                 int NOT NULL,
PETOWNER		          VARCHAR(14));


INSERT INTO PETINF VALUES (1,'DOG','MALE',13,'SHYAM');
INSERT INTO PETINF VALUES (2,'RABBIT','MALE',16,'SAI');
INSERT INTO PETINF VALUES (3,'CAT','FEMALE',17,'SANJU');
INSERT INTO PETINF VALUES (4,'SANKE','MALE',31,'NANI');
INSERT INTO PETINF VALUES (5,'RAT','MALE',18,'SIRISHA');
INSERT INTO PETINF VALUES (6,'PARROT','FEMALE',25,'JUNISHA');

SELECT *FROM PETINF;