SELECT ASCII('A')
SELECT CHAR(65)

DECLARE @START INT
SET @START =65
WHILE (@START<=90)
BEGIN
SELECT CHAR(@START)
SET @START=@START+1
END

SELECT ASCII('a')
SELECT CHAR(97)

DECLARE @START INT
SET @START =97
WHILE (@START<=122)
BEGIN
SELECT CHAR(@START)
SET @START=@START+1
END



SELECT ASCII(0)

DECLARE @START INT
SET @START =48
WHILE (@START<=58)
BEGIN
SELECT CHAR(@START)
SET @START=@START+1
END



SELECT('    SHYAM')
SELECT LTRIM('    SHYAM')

SELECT LTRIM(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;


SELECT('       SHYAM        ')
SELECT RTRIM('    SHYAM      ')

SELECT RTRIM(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;



SELECT LOWER('SHYAM')
SELECT LOWER(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;

SELECT UPPER('shyam')
SELECT upper(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;

SELECT REVERSE('shyam')
SELECT REVERSE(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;

SELECT LEN('shyam')
SELECT LEN(FIRSTNAME) AS FIRSTNAME,LASTNAME FROM EMP;




